spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_wise_master
    username: root
    password: root123456789
  # redis 配置
  redis:
    host: localhost
    port: 6379
    database: 1
    connect-timeout: 5s

# COS 对象存储配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
